### ISSUE TITLE
X11 not starting

### ISSUE THREAD

**Issue by DAB0mB** [selkies-project/docker-nvidia-glx-desktop#29]
Hello! Kudos for this great image. I've been trying to run a deployment on my Kubernetes cluster with nvidia-glx-desktop. Sometimes it works, but sometimes it doesn't (could be how things are cached by the cloud provider?). According to the logs, it looks like the entrypoint scripts are waiting for X11 to start and are stuck in a perpetual loop. Why do you think X11 isn't starting and how can I manually start it?

**Comment by ehfd** [comment]
Hi!
First check the https://github.com/ehfd/docker-nvidia-glx-desktop#troubleshooting section. If that doesn't work for you, please post all three logs located in /tmp.

**Comment by DAB0mB** [comment]
Here are the log files in case of failure, including Xorg.0.log:

[entrypoint-fail-stdout.log](https://github.com/ehfd/docker-nvidia-glx-desktop/files/9551238/entrypoint-fail-stdout.log)
[pulseaudio-fail-stdout.log](https://github.com/ehfd/docker-nvidia-glx-desktop/files/9551239/pulseaudio-fail-stdout.log)
[selkies-gstreamer-fail-stdout.log](https://github.com/ehfd/docker-nvidia-glx-desktop/files/9551240/selkies-gstreamer-fail-stdout.log)
[Xorg.0.fail.log](https://github.com/ehfd/docker-nvidia-glx-desktop/files/9551249/Xorg.0.fail.log)

And here are the log files in case of success:

[entrypoint-stdout.log](https://github.com/ehfd/docker-nvidia-glx-desktop/files/9551253/entrypoint-stdout.log)
[pulseaudio-stdout.log](https://github.com/ehfd/docker-nvidia-glx-desktop/files/9551254/pulseaudio-stdout.log)
[selkies-gstreamer-stdout.log](https://github.com/ehfd/docker-nvidia-glx-desktop/files/9551255/selkies-gstreamer-stdout.log)

Here's the xorg.conf:

[xorg.conf.txt](https://github.com/ehfd/docker-nvidia-glx-desktop/files/9551259/xorg.conf.txt)

To me it seems like everything is setup correctly but there seems to be something with the nodes, I have no access to any of them whatsoever but I can submit a ticket to cloud provider if necessary.

**Comment by ehfd** [comment]
@DAB0mB Thanks for your cooperation. It seems to be that `NVIDIA_DRIVER_CAPABILITIES` is insufficient. Please make sure that it is sent to `all`, or includes `utility,graphics,video,display`, by asking your provider.

**Comment by ehfd** [comment]
If this works, please don't close. I have to update it in the docs.

**Comment by ehfd** [comment]
If not possible, docker-nvidia-egl-desktop may much more likely work.

**Comment by DAB0mB** [comment]
Thank you! Will update shortly once they get back to me

**Comment by ehfd** [comment]
Any updates? @DAB0mB + I explained in https://github.com/ehfd/docker-nvidia-glx-desktop#the-container-doesnt-work what each `NVIDIA_DRIVER_CAPABILITIES` entry does for the container.

**Comment by DAB0mB** [comment]
Hey @ehfd, they're trying to look at it, I've been told that `NVIDIA_DRIVER_CAPABILITIES` is set to `all` by default and that it doesn't seem to be the issue. I will update if I have anything.

**Comment by ehfd** [comment]
Note that the NVIDIA A100 in MIG mode does not support any GUI operations. No OpenGL and Vulkan, no X.Org.

**Comment by ehfd** [comment]
@DAB0mB One more possible cause, is there an X server on the host?

**Comment by ehfd** [comment]
I also updated the container.

**Comment by jfeldman325** [comment]
@DAB0mB We have identified that the issue on CoreWeave is likely due to k8s container memory requirements for the shm feature in x11.  Adding something like the following should resolve the issue:
```
volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /cache
          name: cudaglx-cache-vol
        - mountPath: /home/user
          name: cudaglx-root-vol
      imagePullSecrets:
      - name: render-images
      volumes:
      - emptyDir:
          medium: Memory
        name: dshm
      - name: cudaglx-cache-vol
      - name: cudaglx-root-vol
```

**Comment by ehfd** [comment]
https://github.com/ehfd/docker-nvidia-glx-desktop/blob/main/xgl.yml

This is in the yaml file.

Please reopen if any issues arise again.

**Comment by ehfd** [comment]
I need to add this to the docs too.

**Comment by ehfd** [comment]
Docs added.
