### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by nick008a** [selkies-project/docker-nvidia-glx-desktop#32]
https://github.com/selkies-project/selkies-gstreamer/issues/18

**Comment by ehfd** [comment]
Did not arrive yet. It will arrive in the next release.

**Comment by ehfd** [comment]
In a matter of days. Release is in Selkies.
I am updating the container for Ubuntu 22.04.

**Comment by ehfd** [comment]
It now works, but not 100%.
Please follow https://github.com/selkies-project/selkies-gstreamer/issues/75 and this time the release will be more frequent which means the container will be updated more frequently.
