### ISSUE TITLE
Enable copy paste to and from host

### ISSUE THREAD

**Issue by joshwyatt** [selkies-project/docker-nvidia-glx-desktop#38]
Thanks so much for the wonderful container.

Is there a way we could enable copy and paste to and from the host machine?

**Comment by ehfd** [comment]
If you use HTTPS, it should be possible.

**Comment by ehfd** [comment]
I will create a command line option for https in Selkies.

**Comment by ehfd** [comment]
I see the issue. I can't bring a clipboard to the client.

**Comment by ehfd** [comment]
Works in the latest Selkies-GStreamer release.

**Comment by ehfd** [comment]
Issue came back to me.

**Comment by ehfd** [comment]
This happens only in the glx desktop. Might be an xclip issue.

**Comment by ehfd** [comment]
I have moved the issue to https://github.com/selkies-project/selkies-gstreamer/issues/100 because it's an issue with the remote desktop.
