### ISSUE TITLE
Coexist with Host X11 server 

### ISSUE THREAD

**Issue by ghost** [selkies-project/docker-nvidia-glx-desktop#40]
Is it possible to run this docker image on desktop linux (which already has a running X11 server on the host)?

How should `VIDEO_PORT` be set in this case so that the x server in the container won't interference with the host x11 server?

**Comment by ehfd** [comment]
https://github.com/selkies-project/docker-nvidia-glx-desktop#the-container-does-not-work-if-an-existing-gui-desktop-environment-or-x-server-is-running-in-the-host-outside-the-container--i-want-to-use-this-container-in---privileged-mode-or-with---cap-add-and-do-not-want-other-containers-to-interfere

**Comment by ehfd** [comment]
Yes. But you should see Arch Wiki or other Linux related resources because Intel is outside the scope here.
The instructions I wrote should apparently also help if things don't work.

**Comment by ehfd** [comment]
Extremely easy option should be use the egl desktop. Do need to care about these aspects.

**Comment by ehfd** [comment]
Framerate is slower in unpractically high framerates (>2000 fps) using VirtualGL on EGL, but performance is similar in more practical framerates in practical complex workloads (<300 fps).
