### ISSUE TITLE
Some image manifests appear broken

### ISSUE THREAD

**Issue by remram44** [selkies-project/docker-nvidia-glx-desktop#45]
For example https://github.com/selkies-project/docker-nvidia-glx-desktop/pkgs/container/nvidia-glx-desktop/125387381?tag=18.04-legacy

```
$ docker pull ghcr.io/selkies-project/nvidia-glx-desktop:18.04-legacy
18.04-legacy: Pulling from selkies-project/nvidia-glx-desktop
manifest unknown
```

**Comment by remram44** [comment]
My main problem running this is that I haven't figured out a safe way to share GPUs between containers. Running either the egl image (no GPU) or glx image (reserved GPU) is not very flexible, if you have many users and a limited amount of GPUs. That's not a problem with your project though :wink:

**Comment by ehfd** [comment]
I have rebuilt, pushed, and tested both `18.04-legacy` images. Please leave a comment if any other image is broken.

@remram44 As for you, I will email you in some time. Your question is also of interest to myself as well.

**Comment by remram44** [comment]
Thanks!
