### ISSUE TITLE
Runpod Secure Cloud issues

### ISSUE THREAD

**Issue by BranislavF** [selkies-project/docker-nvidia-glx-desktop#48]
Hello there. I am facing an issue when trying to deploy the container in Secure cloud with runpod.  With community cloud, I can mostly connect without any problems, but with every single secure cloud I am getting errors. I am attaching screenshots of all the logs.

<img width="1326" alt="Screenshot 2023-12-15 at 15 41 07" src="https://github.com/selkies-project/docker-nvidia-glx-desktop/assets/136190291/3a65c5f2-b7c6-4c7f-a938-3b1ff7a2b648">
<img width="936" alt="Screenshot 2023-12-15 at 15 34 17" src="https://github.com/selkies-project/docker-nvidia-glx-desktop/assets/136190291/742b94ae-46a8-4ab5-bd1e-56ca49a6e070">
<img width="1287" alt="Screenshot 2023-12-15 at 15 47 36" src="https://github.com/selkies-project/docker-nvidia-glx-desktop/assets/136190291/63356af0-ecc0-451b-9948-ed02c34c6079">

Le know if there is something I am missing.

**Comment by BranislavF** [comment]
I think this can have something with mounting additional volume in RunPod. AS soon as I remove it, I was able to get that working.

**Comment by ehfd** [comment]
Perhaps the volume mount to /home/user is the concern. I might need to change the source code to ignore the error when chmod to the home directory fails.

**Comment by ehfd** [comment]
https://github.com/selkies-project/docker-nvidia-glx-desktop/commit/09dcc0e0ed429f984380257b4cad2ae9f1495e24

Perhaps this may fix the issue.

**Comment by BranislavF** [comment]
Thank you, this fixed it :)
