### ISSUE TITLE
Startup fails because the nvidia part is unable to write into ro filesystem

### ISSUE THREAD

**Issue by FieldOfRice** [selkies-project/docker-nvidia-glx-desktop#49]
Just tried to get this running with:

`docker run --gpus all --rm -it --name cuda12_vls --tmpfs /dev/shm:rw -e TZ=UTC -e SIZEW=1920 -e SIZEH=1080 -e REFRESH=60 -e DPI=96 -e CDEPTH=24 -e VIDEO_PORT=DFP -e PASSWD=mypasswd -e WEBRTC_ENCODER=nvh264enc -e BASIC_AUTH_PASSWORD=mypasswd -p 8080:8080 ghcr.io/selkies-project/nvidia-glx-desktop:latest`

After some time messages like "... reaped unknown pid ... (exit status1)" appeared.

Inside another Terminal:

`docker exec -it cuda12_vls bash` followed by `tail -f /tmp/entrypoint-stdout---supervisor-fl6x5991.log` reveals this:

`...
* Starting system message bus dbus
   ...done.
Creating directory NVIDIA-Linux-x86_64-525.125.06
Verifying archive integrity... OK
Uncompressing NVIDIA Accelerated Graphics Driver for Linux-x86_64 525.125.06...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
WARNING: You specified the '--no-kernel-modules' command line option, nvidia-installer will not install any kernel modules as part of this driver installation, and it will not remove existing NVIDIA kernel modules not part of an earlier NVIDIA driver installation.  Please ensure that NVIDIA kernel modules matching this driver version are installed separately.
ERROR: Unable to create '/lib/firmware/nvidia/525.125.06/gsp_tu10x.bin' for copying (Read-only file system)
ERROR: Unable to create '/lib/firmware/nvidia/525.125.06/gsp_ad10x.bin' for copying (Read-only file system)
ERROR: Unable to create '/usr/bin/nvidia-smi' for copying (Read-only file system)
ERROR: Unable to create '/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.525.125.06' for copying (Read-only file system)
ERROR: Unable to create '/usr/bin/nvidia-debugdump' for copying (Read-only file system)
ERROR: Unable to create '/usr/lib/x86_64-linux-gnu/libcuda.so.525.125.06' for copying (Read-only file system)
ERROR: Unable to create '/usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.525.125.06' for copying (Read-only file system)
ERROR: Unable to create '/usr/bin/nvidia-persistenced' for copying (Read-only file system)
...
WARNING: Unable to locate/open X configuration file.
Package xorg-server was not found in the pkg-config search path.
Perhaps you should add the directory containing `xorg-server.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xorg-server' found
Option "ProbeAllGpus" "False" added to Screen "Screen0".
Option "BaseMosaic" "False" added to Screen "Screen0".
Option "AllowEmptyInitialConfiguration" "True" added to Screen "Screen0".
New X configuration file written to '/etc/X11/xorg.conf'
Waiting for X socket
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
X.Org X Server 1.21.1.4
X Protocol Version 11, Revision 0
Current Operating System: Linux 451b69ecc3cf 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64
Kernel command line: BOOT_IMAGE=/boot/vmlinuz-6.1.0-13-amd64 root=UUID=019fa11a-2577-4a77-ad19-36cff7b77e87 ro quiet
xorg-server 2:21.1.4-2ubuntu1.7~22.04.5 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.40.0
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/home/user/.local/share/xorg/Xorg.0.log", Time: Tue Dec 26 14:18:35 2023
(==) Using config file: "/etc/X11/xorg.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) no screens found(EE) 
(EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
...`

I tried to start without the "--tmpfs /dev/shm:rw" parameter with same result.
What's wrong? Any pointers?

**Comment by PMohanJ** [comment]
So when you tried to run without the `--tmpfs /dev/shm:rw` flag, did it work?

**Comment by FieldOfRice** [comment]
no it doesn't change anything, independently with or without...

Mohan_J ***@***.***> schrieb am Di., 26. Dez. 2023, 15:48:

**Comment by ehfd** [comment]
I need the contents of /home/user/.local/share/xorg/Xorg.0.log

**Comment by FieldOfRice** [comment]
Those contents are attached with logs.tar.gz file, the files without folder are from /tmp.

   Am Dienstag, 26. Dezember 2023 um 20:36:12 MEZ hat Seungmin Kim ***@***.***> Folgendes geschrieben:  


I need the contents of /home/user/.local/share/xorg/Xorg.0.log

**Comment by FieldOfRice** [comment]
Seem that uploading per email or as an attachment has some problems. The contents of that file are:

`[   197.954] _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
[   197.954] 
X.Org X Server 1.21.1.4
X Protocol Version 11, Revision 0
[   197.954] Current Operating System: Linux e168b46c0599 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64
[   197.954] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-6.1.0-13-amd64 root=UUID=019fa11a-2577-4a77-ad19-36cff7b77e87 ro quiet
[   197.954] xorg-server 2:21.1.4-2ubuntu1.7~22.04.5 (For technical support please see http://www.ubuntu.com/support) 
[   197.954] Current version of pixman: 0.40.0
[   197.954] 	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
[   197.954] Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[   197.954] (==) Log file: "/home/user/.local/share/xorg/Xorg.0.log", Time: Wed Dec 27 12:11:52 2023
[   197.955] (==) Using config file: "/etc/X11/xorg.conf"
[   197.955] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[   197.955] (==) ServerLayout "Layout0"
[   197.955] (**) |-->Screen "Screen0" (0)
[   197.955] (**) |   |-->Monitor "Monitor0"
[   197.955] (**) |   |-->Device "Device0"
[   197.955] (**) |-->Input Device "Keyboard0"
[   197.955] (**) |-->Input Device "Mouse0"
[   197.955] (**) Option "AutoAddGPU" "false"
[   197.955] (==) Automatically adding devices
[   197.955] (==) Automatically enabling devices
[   197.955] (**) Not automatically adding GPU devices
[   197.955] (==) Automatically binding GPU devices
[   197.955] (==) Max clients allowed: 256, resource mask: 0x1fffff
[   197.956] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[   197.956] 	Entry deleted from font path.
[   197.956] (WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[   197.956] 	Entry deleted from font path.
[   197.956] (WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[   197.956] 	Entry deleted from font path.
[   197.956] (WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[   197.956] 	Entry deleted from font path.
[   197.956] (WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[   197.956] 	Entry deleted from font path.
[   197.956] (==) FontPath set to:
	/usr/share/fonts/X11/misc,
	/usr/share/fonts/X11/Type1,
	built-ins
[   197.956] (==) ModulePath set to "/usr/lib/xorg/modules"
[   197.956] (WW) Hotplugging is on, devices using drivers 'kbd', 'mouse' or 'vmmouse' will be disabled.
[   197.956] (WW) Disabling Keyboard0
[   197.956] (WW) Disabling Mouse0
[   197.956] (II) Loader magic: 0x55d93749c020
[   197.956] (II) Module ABI versions:
[   197.956] 	X.Org ANSI C Emulation: 0.4
[   197.956] 	X.Org Video Driver: 25.2
[   197.956] 	X.Org XInput driver : 24.4
[   197.956] 	X.Org Server Extension : 10.0
[   197.958] (EE) systemd-logind: failed to get session: Launch helper exited with unknown return code 1
[   197.959] (II) xfree86: Adding drm device (/dev/dri/card1)
[   197.959] (II) Platform probe for /sys/devices/pci0000:00/0000:00:01.1/0000:01:00.0/drm/card1
[   197.959] (II) xfree86: Adding drm device (/dev/dri/card0)
[   197.959] (II) Platform probe for /sys/devices/pci0000:00/0000:00:08.1/0000:11:00.0/drm/card0
[   197.961] (--) PCI: (1@0:0:0) 10de:2684:1043:88e3 rev 161, Mem @ 0xfb000000/16777216, 0xf000000000/34359738368, 0xf800000000/33554432, I/O @ 0x0000f000/128, BIOS @ 0x????????/524288
[   197.961] (--) PCI:*(17@0:0:0) 1002:164e:1043:8877 rev 196, Mem @ 0xf810000000/268435456, 0xf820000000/2097152, 0xfca00000/524288, I/O @ 0x0000d000/256
[   197.962] (II) LoadModule: "glx"
[   197.962] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[   197.963] (II) Module glx: vendor="X.Org Foundation"
[   197.963] 	compiled for 1.21.1.4, module version = 1.0.0
[   197.963] 	ABI class: X.Org Server Extension, version 10.0
[   197.963] (II) LoadModule: "nvidia"
[   197.963] (II) Loading /usr/lib/xorg/modules/drivers/nvidia_drv.so
[   197.963] (II) Module nvidia: vendor="NVIDIA Corporation"
[   197.963] 	compiled for 1.6.99.901, module version = 1.0.0
[   197.963] 	Module class: X.Org Video Driver
[   197.963] (II) NVIDIA dlloader X Driver  525.125.06  Tue May 30 05:05:32 UTC 2023
[   197.963] (II) NVIDIA Unified Driver for all Supported NVIDIA GPUs
[   197.963] (II) Loading sub module "fb"
[   197.963] (II) LoadModule: "fb"
[   197.963] (II) Module "fb" already built-in
[   197.963] (II) Loading sub module "wfb"
[   197.963] (II) LoadModule: "wfb"
[   197.963] (II) Loading /usr/lib/xorg/modules/libwfb.so
[   197.963] (II) Module wfb: vendor="X.Org Foundation"
[   197.963] 	compiled for 1.21.1.4, module version = 1.0.0
[   197.963] 	ABI class: X.Org ANSI C Emulation, version 0.4
[   197.963] (II) Loading sub module "ramdac"
[   197.963] (II) LoadModule: "ramdac"
[   197.963] (II) Module "ramdac" already built-in
[   197.964] (WW) VGA arbiter: cannot open kernel arbiter, no multi-card support
[   197.964] (**) NVIDIA(0): Depth 24, (--) framebuffer bpp 32
[   197.964] (==) NVIDIA(0): RGB weight 888
[   197.964] (==) NVIDIA(0): Default visual is TrueColor
[   197.964] (==) NVIDIA(0): Using gamma correction (1.0, 1.0, 1.0)
[   197.964] (**) NVIDIA(0): Option "ModeValidation" "NoMaxPClkCheck, NoEdidMaxPClkCheck, NoMaxSizeCheck, NoHorizSyncCheck, NoVertRefreshCheck, NoVirtualSizeCheck, NoExtendedGpuCapabilitiesCheck, NoTotalSizeCheck, NoDualLinkDVICheck, NoDisplayPortBandwidthCheck, AllowNon3DVisionModes, AllowNonHDMI3DModes, AllowNonEdidModes, NoEdidHDMI2Check, AllowDpInterlaced"
[   197.964] (**) NVIDIA(0): Option "ProbeAllGpus" "False"
[   197.964] (**) NVIDIA(0): Option "BaseMosaic" "False"
[   197.964] (**) NVIDIA(0): Option "AllowEmptyInitialConfiguration" "True"
[   197.964] (**) NVIDIA(0): Option "HardDPMS" "False"
[   197.964] (**) NVIDIA(0): Option "ConnectedMonitor" "DFP"
[   197.964] (**) NVIDIA(0): Enabling 2D acceleration
[   197.964] (**) NVIDIA(0): ConnectedMonitor string: "DFP"
[   197.964] (II) Loading sub module "glxserver_nvidia"
[   197.964] (II) LoadModule: "glxserver_nvidia"
[   197.964] (II) Loading /usr/lib/xorg/modules/extensions/libglxserver_nvidia.so
[   197.967] (II) Module glxserver_nvidia: vendor="NVIDIA Corporation"
[   197.967] 	compiled for 1.6.99.901, module version = 1.0.0
[   197.967] 	Module class: X.Org Server Extension
[   197.967] (II) NVIDIA GLX Module  525.125.06  Tue May 30 05:02:50 UTC 2023
[   197.967] (II) NVIDIA: The X server supports PRIME Render Offload.
[   197.967] (--) NVIDIA(0): Valid display device(s) on GPU-0 at PCI:1:0:0
[   197.967] (--) NVIDIA(0):     DFP-0
[   197.967] (--) NVIDIA(0):     DFP-1
[   197.967] (--) NVIDIA(0):     DFP-2
[   197.967] (--) NVIDIA(0):     DFP-3
[   197.967] (--) NVIDIA(0):     DFP-4
[   197.967] (--) NVIDIA(0):     DFP-5
[   197.967] (--) NVIDIA(0):     DFP-6
[   197.967] (--) NVIDIA(0):     DFP-7
[   197.968] (**) NVIDIA(0): Using ConnectedMonitor string "DFP-0".
[   197.968] (WW) NVIDIA: No DRM device: No direct render devices found.
[   197.968] (II) NVIDIA(0): NVIDIA GPU NVIDIA GeForce RTX 4090 (AD102-A) at PCI:1:0:0
[   197.968] (II) NVIDIA(0):     (GPU-0)
[   197.968] (--) NVIDIA(0): Memory: 25153536 kBytes
[   197.968] (--) NVIDIA(0): VideoBIOS: 95.02.3c.40.b5
[   197.968] (II) NVIDIA(0): Detected PCI Express Link width: 16X
[   197.968] (EE) NVIDIA(GPU-0): Failed to acquire modesetting permission.
[   197.968] (EE) NVIDIA(0): Failing initialization of X screen
[   197.970] (II) UnloadModule: "nvidia"
[   197.970] (II) UnloadSubModule: "glxserver_nvidia"
[   197.970] (II) Unloading glxserver_nvidia
[   197.970] (II) UnloadSubModule: "wfb"
[   197.970] (EE) Screen(s) found, but none have a usable configuration.
[   197.970] (EE) 
Fatal server error:
[   197.970] (EE) no screens found(EE) 
[   197.970] (EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
[   197.970] (EE) Please also check the log file at "/home/user/.local/share/xorg/Xorg.0.log" for additional information.
[   197.970] (EE) 
[   197.970] (EE) Server terminated with error (1). Closing log file.
`

**Comment by ehfd** [comment]
There are a lot of possibilities, but first, do you happen to have the NVIDIA server drivers installed?

**Comment by FieldOfRice** [comment]
the nvidia driver is installed.

Seungmin Kim ***@***.***> schrieb am Fr., 29. Dez. 2023,
02:22:

**Comment by ehfd** [comment]
Next: https://github.com/selkies-project/docker-nvidia-glx-desktop#the-container-does-not-work-if-an-existing-gui-desktop-environment-or-x-server-is-running-in-the-host-outside-the-container--i-want-to-use-this-container-in---privileged-mode-or-with---cap-add-and-do-not-want-other-containers-to-interfere

**Comment by ehfd** [comment]
The EGL desktop is without that restriction. We are trying to understand other ways to work around that restriction.
