### ISSUE TITLE
touch does not support sub directories.

### ISSUE THREAD

**Issue by HansLarsen** [selkies-project/docker-nvidia-glx-desktop#52]
I'm attempting to launch the container, however the script, /etc/selkies-gstreamer-entrypoint.sh crashes with the error: 
`sudo touch /dev/input/{js0,js1,js2,js3}
touch: cannot touch '/dev/input/js0': No such file or directory
touch: cannot touch '/dev/input/js2': No such file or directory
touch: cannot touch '/dev/input/js3': No such file or directory`

it seems that touch dosent support creating files in subdirectories like this, as cd'ing into the directory and running touch {js0,js1,js2,js3} works fine.

![billede](https://github.com/selkies-project/docker-nvidia-glx-desktop/assets/45482017/21b957e7-b8ec-4054-9be6-a0fc900ffa49)

I'm running this on a ubuntu 22.04 host with the nvidia container toolbox.

**Comment by ehfd** [comment]
Understood. Will fix. Thank you.

**Comment by ehfd** [comment]
Please check the fix.

**Comment by ehfd** [comment]
Closing for now. Please reopen if there are issues.
