### ISSUE TITLE
Malformed BUS_ID. Typo with '@' extra character?

### ISSUE THREAD

**Issue by alexeadem** [selkies-project/docker-nvidia-glx-desktop#55]
'@'  extra character in BUS_ID

https://github.com/selkies-project/docker-nvidia-glx-desktop/blob/b506c323db4360998584b618921ef81307224f22/entrypoint.sh#L124C1-L124C97

here:
```
++ nvidia-smi --query-gpu=uuid --format=csv,noheader
++ head -n1
+ GPU_SELECT=GPU-24dd362d-7da3-0b0d-8689-dd9f090aaf48
++ nvidia-smi --query-gpu=pci.bus_id --id=GPU-24dd362d-7da3-0b0d-8689-dd9f090aaf48 --format=csv,noheader
++ head -n1
+ HEX_ID=00000000:01:00.0
+ echo 00000000:01:00.0
00000000:01:00.0
+ IFS=:.
+ ARR_ID=($HEX_ID)
+ unset IFS
+ BUS_ID=PCI:1@0:0:0
+ echo PCI:1@0:0:0
PCI:1@0:0:0

```

`PCI:1@0:0:0 should be PCI:10:0:0`

**Comment by ehfd** [comment]
https://github.com/selkies-project/docker-nvidia-glx-desktop/issues/50

This was suggested by an NVIDIA employee for datacenter environment conditions.

Does it not work? I need to understand the issue.

**Comment by ehfd** [comment]
Let's separate whatever your issue is with the BUS ID thing. There should not be an issue with BUS ID.

**Comment by alexeadem** [comment]
> #50
> 
> This was suggested by an NVIDIA employee for datacenter environment conditions.
> 
> Does it not work? I need to understand the issue.

Got it. Not issues with or without the '@'.
