### ISSUE TITLE
Trouble running the container with Podman

### ISSUE THREAD

**Issue by jave** [selkies-project/docker-nvidia-glx-desktop#57]
I'm having problem running the container, see error below.

 docker run --rm --name xgl -it -d  --device nvidia.com/gpu=all --tmpfs /dev/shm:rw -e TZ=UTC -e DISPLAY_SIZEW=1920 -e DISPLAY_SIZEH=1080 -e DISPLAY_REFRESH=60 -e DISPLAY_DPI=96 -e DISPLAY_CDEPTH=24 -e PASSWD=xxx -e SELKIES_ENCODER=nvh264$

 New password: Retype new password: passwd: password updated successfully
 touch: cannot touch '/dev/input/js0': No such file or directory
 touch: cannot touch '/dev/input/js1': No such file or directory
 touch: cannot touch '/dev/input/js2': No such file or directory
 touch: cannot touch '/dev/input/js3': No such file or directory
 /etc/entrypoint.sh: line 124: 16#: invalid integer constant (error token is "16#")
 nvidia-xconfig: option "--busid" requires an argument.

 Invalid commandline, please run `nvidia-xconfig --help` for usage
 information.

 ^[]0;ubuntu@86cfdd58dad0: /tmp^Gubuntu@86cfdd58dad0:/tmp$ nvidia-smi
 nvidia-smi
 Sun Jul 28 15:57:27 2024
 +-----------------------------------------------------------------------------------------+
 | NVIDIA-SMI 555.58.02              Driver Version: 555.58.02      CUDA Version: 12.5     |
 |-----------------------------------------+------------------------+----------------------+
 | GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
 | Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
 |                                         |                        |               MIG M. |
 |=========================================+========================+======================|
 |   0  NVIDIA GeForce RTX 4090        Off |   00000000:01:00.0 Off |                  Off |
 | 32%   30C    P8             15W /  450W |      62MiB /  24564MiB |      0%      Default |
 |                                         |                        |                  N/A |
 +-----------------------------------------+------------------------+----------------------+

 +-----------------------------------------------------------------------------------------+
 | Processes:                                                                              |
 |  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
 |        ID   ID                                                               Usage      |
 |=========================================================================================|
 +-----------------------------------------------------------------------------------------+

**Comment by ehfd** [comment]
Apparrently, you are using the CDI interface?

**Comment by ehfd** [comment]
`--device nvidia.com/gpu=all`

This might not be valid syntax.

**Comment by ehfd** [comment]
`docker run --rm -ti --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=nvidia.com/gpu=all`

I think this is the valid syntax for Docker with CDI (your command works for podman). Else, `--gpus all` or `--gpus '"device=1,2"'` is correct.

**Comment by jave** [comment]
Yes, nvidia encouraged CDI: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/cdi-support.html

Im using podman, there is a docker alias to podman on my system.

I tried various variants of the flags, --gpus=all, --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=nvidia.com/gpu=all

etc...

i didnt get anything to work so far

I tried the sibling egl image, and that at least starts, and I can get so far as to get a "connecting" message in the webinterface, then it never completes.

**Comment by jave** [comment]
This actually works, for the egl container!

ocker run --rm  --name egl -it -d --gpus all -e NVIDIA_VISIBLE_DEVICES=nvidia.com/gpu=all --device nvidia.com/gpu=all --tmpfs /dev/shm:rw -e TZ=UTC -e DISPLAY_SIZEW=1920 -e DISPLAY_SIZEH=1080 -e DISPLAY_REFRESH=60 -e DISPLAY_DPI=96 -e DISPLAY_CDEPTH=24 -e PASSWD=xxx -e SELKIES_ENCODER=nvh264enc -e SELKIES_VIDEO_BITRATE=8000 -e SELKIES_FRAMERATE=60 -e SELKIES_AUDIO_BITRATE=128000 -e SELKIES_BASIC_AUTH_PASSWORD=mypasswd -p 8080:8080 ghcr.io/selkies-project/nvidia-egl-desktop:latest

**Comment by ehfd** [comment]
I'll check the part of the script that can error in podman.

**Comment by ehfd** [comment]
Alternatively, try specifying the ID like `nvidia.com/gpu=0`

**Comment by ehfd** [comment]
https://github.com/selkies-project/docker-nvidia-glx-desktop/commit/c70349b64b016d22268558c2108c0a2079f04e89

More fixes

**Comment by ehfd** [comment]
```bash
podman run --name xgl -it -d --device nvidia.com/gpu=all --tmpfs /dev/shm:rw -e TZ=UTC -e DISPLAY_SIZEW=1920 -e DISPLAY_SIZEH=1080 -e DISPLAY_REFRESH=60 -e DISPLAY_DPI=96 -e DISPLAY_CDEPTH=24 -e PASSWD=mypasswd -e SELKIES_ENCODER=nvh264enc -e SELKIES_VIDEO_BITRATE=8000 -e SELKIES_FRAMERATE=60 -e SELKIES_AUDIO_BITRATE=128000 -e SELKIES_BASIC_AUTH_PASSWORD=mypasswd -p 3478:3478 -p 8080:8080 ghcr.io/selkies-project/nvidia-glx-desktop:latest
```

Confirmed working.
