### ISSUE TITLE
Connection refused to 127.0.0.1:8080

### ISSUE THREAD

**Issue by Fisher-Wang** [selkies-project/docker-nvidia-glx-desktop#59]
## How to reproduce
1. 
     ```
     git clone https://github.com/selkies-project/docker-nvidia-glx-desktop
     cd docker-nvidia-glx-desktop
     ```

2. uncomment `network_mode: host` in `docker-compose.yml`
3. `sudo docker compose up -d`
4. `nc -zv localhost 8080`

    Then I got the error `nc: connect to localhost (127.0.0.1) port 8080 (tcp) failed: Connection refused`

5. Open a brower and visit http://127.0.0.1:8080

   Then I got this
   ![image](https://github.com/user-attachments/assets/f5b4a5b5-1d30-4e99-8289-7e8f2cbf58f6)
   
Could you help me run it correctly? Thank you very much

**Comment by PMohanJ** [comment]
Please post support related question either on Discord or Github Discussions.
> Please read [Troubleshooting](https://github.com/selkies-project/docker-nvidia-glx-desktop#troubleshooting) first, then use [Discord](https://discord.gg/wDNGDeSW5F) or [GitHub Discussions](https://github.com/selkies-project/docker-nvidia-glx-desktop/discussions) for support questions. Please only use [Issues](https://github.com/selkies-project/docker-nvidia-glx-desktop/issues) for technical inquiries or bug reports

**Comment by Fisher-Wang** [comment]
OK I will post it there. I'm sorry for the wrong place.

**Comment by Fisher-Wang** [comment]
I post the problem [here](https://github.com/selkies-project/docker-nvidia-glx-desktop/discussions/60#discussion-7107515).
