### ISSUE TITLE
`Connection failed`

### ISSUE THREAD

**Issue by jmakov** [selkies-project/docker-nvidia-glx-desktop#63]
Running docker command from the README, but using `podman` instead: ` podman run --name xgl -it -d --gpus 1 --tmpfs /dev/shm:rw -e TZ=UTC -e DISPLAY_SIZEW=1920 -e DISPLAY_SIZEH=1080 -e DISPLAY_REFRESH=60 -e DISPLAY_DPI=96 -e DISPLAY_CDEPTH=24 -e PASSWD=mypasswd -e SELKIES_ENCODER=nvh264enc -e SELKIES_VIDEO_BITRATE=8000 -e SELKIES_FRAMERATE=60 -e SELKIES_AUDIO_BITRATE=128000 -e SELKIES_BASIC_AUTH_PASSWORD=mypasswd -p 8080:8080 ghcr.io/selkies-project/nvidia-glx-desktop:latest`. 
When connecting I see:
1. "registering with server, peer ID 1"
2. "registering with server, peer ID 3"
3. waiting for stream
4. connection failed

I verified this works: `podman run --rm --device nvidia.com/gpu=all --security-opt=label=disable ubuntu nvidia-smi -L`. Not sure what went wrong. `podman` logs:
```
2024-10-27 22:07:26,100 WARN No file matches via include "/etc/supervisor/conf.d/*.conf"
2024-10-27 22:07:26,102 INFO RPC interface 'supervisor' initialized
2024-10-27 22:07:26,102 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2024-10-27 22:07:26,102 INFO supervisord started with pid 1
2024-10-27 22:07:27,105 INFO spawned: 'dbus' with pid 26
2024-10-27 22:07:27,106 INFO spawned: 'entrypoint' with pid 27
2024-10-27 22:07:27,107 INFO spawned: 'kasmvnc' with pid 28
2024-10-27 22:07:27,108 INFO spawned: 'selkies-gstreamer' with pid 29
2024-10-27 22:07:27,110 INFO spawned: 'nginx' with pid 31
2024-10-27 22:07:27,110 INFO spawned: 'pipewire' with pid 37
2024-10-27 22:07:27,112 INFO spawned: 'pipewire-pulse' with pid 43
2024-10-27 22:07:27,113 INFO spawned: 'wireplumber' with pid 47
2024-10-27 22:07:27,317 INFO reaped unknown pid 77 (exit status 0)
2024-10-27 22:07:27,590 INFO reaped unknown pid 140 (exit status 1)
2024-10-27 22:07:28,119 INFO success: dbus entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-10-27 22:07:28,119 INFO success: entrypoint entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-10-27 22:07:28,119 INFO success: kasmvnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-10-27 22:07:28,119 INFO success: selkies-gstreamer entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-10-27 22:07:28,119 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-10-27 22:07:28,119 INFO success: pipewire entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-10-27 22:07:28,119 INFO success: pipewire-pulse entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-10-27 22:07:28,119 INFO success: wireplumber entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-10-27 22:07:28,391 INFO reaped unknown pid 160 (exit status 1)
2024-10-27 22:07:29,393 INFO reaped unknown pid 164 (exit status 1)
2024-10-27 22:07:37,478 INFO reaped unknown pid 324 (exit status 0)
2024-10-27 22:07:37,505 INFO reaped unknown pid 428 (exit status 1)
2024-10-27 22:07:38,293 INFO reaped unknown pid 504 (exit status 0)
2024-10-27 22:07:38,293 INFO reaped unknown pid 515 (exit status 0)
2024-10-27 22:07:38,875 INFO reaped unknown pid 568 (exit status 0)
2024-10-27 22:07:39,780 INFO reaped unknown pid 578 (exit status 0)
2024-10-27 22:07:40,572 INFO reaped unknown pid 735 (exit status 0)
2024-10-27 22:07:42,005 INFO reaped unknown pid 775 (exit status 0)
```
Same behavior for `docker-nvidia-egl-desktop`

**Comment by PMohanJ** [comment]
I never tried with podman, but it should work fine. I suspect it's the network issue regarding the TURN server. For more detailed logs, you could check inside the container at `/tmp` location; log files starting with names `entrypoint-*`, `selkies-entrypoint-*` are needed.
Mean while if it's possible try with docker as well and let us know the behaviour.

**Comment by ehfd** [comment]
It's the TURN server issue. https://github.com/selkies-project/selkies-gstreamer/blob/main/docs/firewall.md#turn-server

**Comment by jmakov** [comment]
Ran with docker, can't even connect. Docker logs:
`/tmp/entrypoint.log`:
<details>
```
New password: Retype new password: passwd: password updated successfully
mkdir: cannot create directory ‘/dev/input’: Permission denied
touch: cannot touch '/dev/input/js0': No such file or directory
touch: cannot touch '/dev/input/js1': No such file or directory
touch: cannot touch '/dev/input/js2': No such file or directory
touch: cannot touch '/dev/input/js3': No such file or directory
chmod: changing permissions of '/dev/input/js0': Operation not permitted
chmod: changing permissions of '/dev/input/js1': Operation not permitted
chmod: changing permissions of '/dev/input/js2': Operation not permitted
chmod: changing permissions of '/dev/input/js3': Operation not permitted
Creating directory NVIDIA-Linux-x86_64-560.35.03
Verifying archive integrity... OK
Uncompressing NVIDIA Accelerated Graphics Driver for Linux-x86_64 560.35.03....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................>

WARNING: You specified the '--no-kernel-modules' command line option, nvidia-installer will not install any kernel modules as part of this driver installation, and it will not remove existing NVIDIA kernel modules not part of an earlier NVIDIA driver installation.  Please ensure that NVIDIA kernel modules matching this driver version are installed separately.

/etc/entrypoint.sh: line 117: printf: 0x: invalid hex number
/etc/entrypoint.sh: line 117: printf: Make: invalid number
/etc/entrypoint.sh: line 117: printf: sure: invalid number
/etc/entrypoint.sh: line 117: printf: that: invalid number
/etc/entrypoint.sh: line 117: printf: the: invalid number
/etc/entrypoint.sh: line 117: printf: latest: invalid number
/etc/entrypoint.sh: line 117: printf: NVIDIA: invalid number
/etc/entrypoint.sh: line 117: printf: driver: invalid number
/etc/entrypoint.sh: line 117: printf: is: invalid number
/etc/entrypoint.sh: line 117: printf: installed: invalid number
/etc/entrypoint.sh: line 117: printf: and: invalid number
/etc/entrypoint.sh: line 117: printf: running: invalid number
/etc/entrypoint.sh: line 117: printf: 0xNVIDIA-SMI: invalid hex number
/etc/entrypoint.sh: line 117: printf: has: invalid number
/etc/entrypoint.sh: line 117: printf: failed: invalid number
/etc/entrypoint.sh: line 117: printf: because: invalid number
/etc/entrypoint.sh: line 117: printf: it: invalid number
/etc/entrypoint.sh: line 117: printf: couldn't: invalid number
/etc/entrypoint.sh: line 117: printf: communicate: invalid number
/etc/entrypoint.sh: line 117: printf: with: invalid number
/etc/entrypoint.sh: line 117: printf: the: invalid number
/etc/entrypoint.sh: line 117: printf: NVIDIA: invalid number
/etc/entrypoint.sh: line 117: printf: driver: invalid number
/etc/entrypoint.sh: line 117: printf: 0x: invalid hex number
/etc/entrypoint.sh: line 117: printf: 0x: invalid hex number
New password: Retype new password: passwd: password updated successfully
chmod: changing permissions of '/dev/input/js0': Operation not permitted
chmod: changing permissions of '/dev/input/js1': Operation not permitted
chmod: changing permissions of '/dev/input/js2': Operation not permitted
chmod: changing permissions of '/dev/input/js3': Operation not permitted
/etc/entrypoint.sh: line 117: printf: 0x: invalid hex number
/etc/entrypoint.sh: line 117: printf: Make: invalid number
/etc/entrypoint.sh: line 117: printf: sure: invalid number
/etc/entrypoint.sh: line 117: printf: that: invalid number
/etc/entrypoint.sh: line 117: printf: the: invalid number
/etc/entrypoint.sh: line 117: printf: latest: invalid number
/etc/entrypoint.sh: line 117: printf: NVIDIA: invalid number
/etc/entrypoint.sh: line 117: printf: driver: invalid number
/etc/entrypoint.sh: line 117: printf: is: invalid number
/etc/entrypoint.sh: line 117: printf: installed: invalid number
/etc/entrypoint.sh: line 117: printf: and: invalid number
/etc/entrypoint.sh: line 117: printf: running: invalid number
/etc/entrypoint.sh: line 117: printf: 0xNVIDIA-SMI: invalid hex number
/etc/entrypoint.sh: line 117: printf: has: invalid number
/etc/entrypoint.sh: line 117: printf: failed: invalid number
/etc/entrypoint.sh: line 117: printf: because: invalid number
/etc/entrypoint.sh: line 117: printf: it: invalid number
/etc/entrypoint.sh: line 117: printf: couldn't: invalid number
/etc/entrypoint.sh: line 117: printf: communicate: invalid number
/etc/entrypoint.sh: line 117: printf: with: invalid number
/etc/entrypoint.sh: line 117: printf: the: invalid number
/etc/entrypoint.sh: line 117: printf: NVIDIA: invalid number
/etc/entrypoint.sh: line 117: printf: driver: invalid number
/etc/entrypoint.sh: line 117: printf: 0x: invalid hex number
/etc/entrypoint.sh: line 117: printf: 0x: invalid hex number
New password: Retype new password: passwd: password updated successfully
chmod: changing permissions of '/dev/input/js0': Operation not permitted
chmod: changing permissions of '/dev/input/js1': Operation not permitted
chmod: changing permissions of '/dev/input/js2': Operation not permitted
chmod: changing permissions of '/dev/input/js3': Operation not permitted
/etc/entrypoint.sh: line 117: printf: 0x: invalid hex number
...
```
</details>
`/tmp/selkies-gstreamer-entrypoint.log`
<details>
```
Waiting for X Socket
0: : Config file found: /etc/turnserver.conf
0: : Listener address to use: 0.0.0.0
0: : Listener address to use: ::
0: : Config file found: /etc/turnserver.conf
0: : 
RFC 3489/5389/5766/5780/6062/6156 STUN/TURN Server
Version Coturn-4.6.1 'Gorst'
0: : 
Max number of open files/sockets allowed for this process: 1048576
0: : 
Due to the open files/sockets limitation,
max supported number of TURN Sessions possible is: 524000 (approximately)
0: : 

==== Show him the instruments, Practical Frost: ====

0: : TLS supported
0: : DTLS supported
0: : DTLS 1.2 supported
0: : TURN/STUN ALPN supported
0: : Third-party authorization (oAuth) supported
0: : GCM (AEAD) supported
0: : OpenSSL compile-time version: OpenSSL 3.0.13 30 Jan 2024 (0x300000d0)
0: : 
0: : SQLite supported, default database location is /var/lib/turn/turndb
0: : Redis supported
0: : PostgreSQL supported
0: : MySQL supported
0: : MongoDB is not supported
0: : 
0: : Default Net Engine version: 3 (UDP thread per CPU core)

=====================================================

0: : Domain name:
0: : Default realm: example.com
0: : CONFIG WARNING: allow_loopback_peers opens a possible security vulnerability. Do not use in production!!
0: : WARNING: cannot find certificate file: turn_server_cert.pem (1)
0: : WARNING: cannot start TLS and DTLS listeners because certificate file is not set properly
0: : WARNING: cannot find private key file: turn_server_pkey.pem (1)
0: : WARNING: cannot start TLS and DTLS listeners because private key file is not set properly
0: : Relay address to use: 0.0.0.0
0: : Relay address to use: ::
0: : pid file created: /tmp/runtime-ubuntu/turnserver.pid
0: : IO method (main listener thread): epoll (with changelist)
0: : INFO: RFC5780 disabled! /NAT behavior discovery/
0: : Wait for relay ports initialization...
0: :   relay 0.0.0.0 initialization...
0: :   relay 0.0.0.0 initialization done
0: :   relay :: initialization...
0: :   relay :: initialization done
0: : Relay ports initialization done
0: : IO method (general relay thread): epoll (with changelist)
0: : IO method (general relay thread): epoll (with changelist)
0: : turn server id=0 created
0: : IO method (general relay thread): epoll (with changelist)
0: : IO method (general relay thread): epoll (with changelist)
0: : IPv4. SCTP listener opened on : 0.0.0.0:3478
0: : turn server id=1 created
0: : IO method (general relay thread): epoll (with changelist)
0: : turn server id=2 created
0: : IO method (general relay thread): epoll (with changelist)
0: : turn server id=3 created
0: : IO method (general relay thread): epoll (with changelist)
0: : IPv4. SCTP listener opened on : 0.0.0.0:3478
0: : turn server id=4 created
0: : IPv4. SCTP listener opened on : 0.0.0.0:3478
0: : turn server id=5 created
0: : IO method (general relay thread): epoll (with changelist)
0: : IPv4. TCP listener opened on : 0.0.0.0:3478
0: : IPv4. SCTP listener opened on : 0.0.0.0:3478
0: : IO method (general relay thread): epoll (with changelist)
0: : IPv4. TCP listener opened on : 0.0.0.0:3478
0: : IO method (general relay thread): epoll (with changelist)
0: : turn server id=6 created
0: : IPv4. SCTP listener opened on : 0.0.0.0:3478
...
```
</details>

**Comment by ehfd** [comment]
Try pulling the container again and retry...

**Comment by jmakov** [comment]
Tested again and runs when adding `--network=host`: `podman run --network=host --name xgl -it -d --gpus 1 --tmpfs /dev/shm:rw -e TZ=UTC -e DISPLAY_SIZEW=1920 -e DISPLAY_SIZEH=1080 -e DISPLAY_REFRESH=60 -e DISPLAY_DPI=96 -e DISPLAY_CDEPTH=24 -e PASSWD=mypasswd -e SELKIES_ENCODER=nvh264enc -e SELKIES_VIDEO_BITRATE=8000 -e SELKIES_FRAMERATE=60 -e SELKIES_AUDIO_BITRATE=128000 -e SELKIES_BASIC_AUTH_PASSWORD=mypasswd -p 8080:8080 ghcr.io/selkies-project/nvidia-glx-desktop:latest`

**Comment by jmakov** [comment]
But on another node, same distro, it doesn't start: `Unable to connect`.

**Comment by jmakov** [comment]
> You most likely need to read the TURN server documentation and expose the adequate ports.

Is this the case even if using `--network=host`?

<details>
<summary>/tmp/entrypoint.log</summary>
New password: Retype new password: passwd: password updated successfully
mkdir: cannot create directory ‘/dev/input’: Permission denied
touch: cannot touch '/dev/input/js0': No such file or directory
touch: cannot touch '/dev/input/js1': No such file or directory
touch: cannot touch '/dev/input/js2': No such file or directory
touch: cannot touch '/dev/input/js3': No such file or directory
chmod: changing permissions of '/dev/input/js0': Operation not permitted
chmod: changing permissions of '/dev/input/js1': Operation not permitted
chmod: changing permissions of '/dev/input/js2': Operation not permitted
chmod: changing permissions of '/dev/input/js3': Operation not permitted
Creating directory NVIDIA-Linux-x86_64-550.120
Verifying archive integrity... OK
Uncompressing NVIDIA Accelerated Graphics Driver for Linux-x86_64 550.120......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................>

WARNING: You specified the '--no-kernel-modules' command line option, nvidia-installer will not install any kernel modules as part of this driver installation, and it will not remove existing NVIDIA kernel modules not part of an earlier NVIDIA driver installation.  Please ensure that NVIDIA kernel modules matching this driver version are installed separately.


ERROR: Unable to delete existing file '/lib/firmware/nvidia/550.120/gsp_tu10x.bin' (Permission denied)


ERROR: Unable to delete existing file '/lib/firmware/nvidia/550.120/gsp_ga10x.bin' (Permission denied)


ERROR: Unable to delete existing file '/usr/bin/nvidia-smi' (Device or resource busy)


ERROR: Unable to delete existing file '/usr/bin/nvidia-debugdump' (Device or resource busy)


ERROR: Unable to delete existing file '/usr/bin/nvidia-cuda-mps-control' (Device or resource busy)


ERROR: Unable to delete existing file '/usr/bin/nvidia-cuda-mps-server' (Device or resource busy)


ERROR: Unable to delete existing file '/usr/bin/nvidia-persistenced' (Device or resource busy)


ERROR: Unable to delete existing file '/etc/vulkan/icd.d/nvidia_icd.json' (Device or resource busy)


ERROR: Unable to delete existing file '/etc/vulkan/implicit_layer.d/nvidia_layers.json' (Device or resource busy)


ERROR: Unable to create '/usr/share/nvidia/nvidia-application-profiles-550.120-rc' for copying (Permission denied)


ERROR: Unable to create '/usr/share/nvidia/nvidia-application-profiles-550.120-key-documentation' for copying (Permission denied)


ERROR: Unable to delete existing file '/usr/share/glvnd/egl_vendor.d/10_nvidia.json' (Device or resource busy)


ERROR: Unable to delete existing file '/usr/share/egl/egl_external_platform.d/10_nvidia_wayland.json' (Permission denied)


ERROR: Unable to delete existing file '/usr/share/egl/egl_external_platform.d/15_nvidia_gbm.json' (Permission denied)


ERROR: Unable to delete existing file '/usr/lib/xorg/modules/drivers/nvidia_drv.so' (Device or resource busy)


ERROR: Unable to delete existing file '/usr/share/nvidia/nvoptix.bin' (Permission denied)


WARNING: The installed file '/lib/firmware/nvidia/550.120/gsp_tu10x.bin' has permissions 0644, but it was installed with permissions 0444.


WARNING: The installed file '/lib/firmware/nvidia/550.120/gsp_ga10x.bin' has permissions 0644, but it was installed with permissions 0444.


WARNING: Unable to find installed file '/usr/share/nvidia/nvidia-application-profiles-550.120-rc' (No such file or directory).


WARNING: Unable to find installed file '/usr/share/nvidia/nvidia-application-profiles-550.120-key-documentation' (No such file or directory).


WARNING: The installed file '/usr/share/nvidia/nvoptix.bin' has permissions 0755, but it was installed with permissions 0444.


WARNING: Unable to locate/open X configuration file.

Option "ProbeAllGpus" "False" added to Screen "Screen0".
Option "IncludeImplicitMetaModes" "True" added to Screen "Screen0".
Option "ModeDebug" "True" added to Screen "Screen0".
Option "BaseMosaic" "False" added to Screen "Screen0".
Option "AllowEmptyInitialConfiguration" "True" added to Screen "Screen0".
New X configuration file written to '/etc/X11/xorg.conf'

ln: failed to create symbolic link '/dev/tty7': Permission denied
Waiting for X Socket
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.21.1.11
X Protocol Version 11, Revision 0
Current Operating System: Linux node2 6.6.54-2-MANJARO #1 SMP PREEMPT_DYNAMIC Tue Oct  8 03:11:08 UTC 2024 x86_64
Kernel command line: BOOT_IMAGE=/@/boot/vmlinuz-6.6-x86_64 root=UUID=55bf0124-97bd-4b05-95ab-6ab1db05ec60 rw rootflags=subvol=@ quiet splash udev.log_priority=3 elevator=deadline noibrs noibpb nopti nospectre_v2 nospectre_v1 l1tf=off nospec_store_bypass_disable no_stf_barrier mds=off tsx=on tsx_async_abort=off mitigations=off amd_iommu=on iommu=pt
xorg-server 2:21.1.12-1ubuntu1 (For technical support please see http://www.ubuntu.com/support)
Current version of pixman: 0.42.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/home/ubuntu/.local/share/xorg/Xorg.20.log", Time: Tue Oct 29 10:27:36 2024
(==) Using config file: "/etc/X11/xorg.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE)
Fatal server error:
(EE) no screens found(EE)
(EE)
Please consult the The X.Org Foundation support
         at http://wiki.x.org
 for help.
(EE) Please also check the log file at "/home/ubuntu/.local/share/xorg/Xorg.20.log" for additional information.
(EE)
(EE) Server terminated with error (1). Closing log file.

</details>
<details>
<summary>/tmp/selkies-gstreamer-entrypoint.log</summary>
Waiting for X Socket
0: : Config file found: /etc/turnserver.conf
0: : Listener address to use: 0.0.0.0
0: : Listener address to use: ::
0: : Config file found: /etc/turnserver.conf
0: :
RFC 3489/5389/5766/5780/6062/6156 STUN/TURN Server
Version Coturn-4.6.1 'Gorst'
0: :
Max number of open files/sockets allowed for this process: 1048576
0: :
Due to the open files/sockets limitation,
max supported number of TURN Sessions possible is: 524000 (approximately)
0: :

==== Show him the instruments, Practical Frost: ====

0: : TLS supported
0: : DTLS supported
0: : DTLS 1.2 supported
0: : TURN/STUN ALPN supported
0: : Third-party authorization (oAuth) supported
0: : GCM (AEAD) supported
0: : OpenSSL compile-time version: OpenSSL 3.0.13 30 Jan 2024 (0x300000d0)
0: :
0: : SQLite supported, default database location is /var/lib/turn/turndb
0: : Redis supported
0: : PostgreSQL supported
0: : MySQL supported
0: : MongoDB is not supported
0: :
0: : Default Net Engine version: 3 (UDP thread per CPU core)

=====================================================

0: : Domain name:
0: : Default realm: example.com
0: : CONFIG WARNING: allow_loopback_peers opens a possible security vulnerability. Do not use in production!!
0: : WARNING: cannot find certificate file: turn_server_cert.pem (1)
0: : WARNING: cannot start TLS and DTLS listeners because certificate file is not set properly
0: : WARNING: cannot find private key file: turn_server_pkey.pem (1)
0: : WARNING: cannot start TLS and DTLS listeners because private key file is not set properly
0: : Relay address to use: 0.0.0.0
0: : Relay address to use: ::
0: : pid file created: /tmp/runtime-ubuntu/turnserver.pid
0: : IO method (main listener thread): epoll (with changelist)
0: : INFO: RFC5780 disabled! /NAT behavior discovery/
0: : Wait for relay ports initialization...
0: :   relay 0.0.0.0 initialization...
0: :   relay 0.0.0.0 initialization done
0: :   relay :: initialization...
0: :   relay :: initialization done
0: : Relay ports initialization done
0: : IO method (general relay thread): epoll (with changelist)
0: : IO method (general relay thread): epoll (with changelist)
0: : IO method (general relay thread): epoll (with changelist)
0: : IO method (general relay thread): epoll (with changelist)
0: : turn server id=1 created
0: : turn server id=0 created
0: : IO method (general relay thread): epoll (with changelist)
0: : IO method (general relay thread): epoll (with changelist)
0: : IPv4. SCTP listener opened on : 0.0.0.0:3478
0: : turn server id=2 created
0: : IPv4. SCTP listener opened on : 0.0.0.0:3478
0: : IO method (general relay thread): epoll (with changelist)
0: : IO method (general relay thread): epoll (with changelist)
0: : turn server id=5 created
0: : IPv4. SCTP listener opened on : 0.0.0.0:3478
0: : turn server id=4 created
0: : IO method (general relay thread): epoll (with changelist)
0: : IO method (general relay thread): epoll (with changelist)
0: : IO method (general relay thread): epoll (with changelist)
0: : IPv4. TCP listener opened on : 0.0.0.0:3478
0: : turn server id=6 created
0: : turn server id=10 created
0: : turn server id=3 created
0: : IPv6. SCTP listener opened on : :::3478
0: : turn server id=3 created
0: : IPv6. SCTP listener opened on : :::3478
0: : IPv4. SCTP listener opened on : 0.0.0.0:3478
0: : IO method (general relay thread): epoll (with changelist)
0: : turn server id=9 created
0: : IPv4. SCTP listener opened on : 0.0.0.0:3478
0: : IO method (general relay thread): epoll (with changelist)
0: : IPv4. TCP listener opened on : 0.0.0.0:3478
0: : IO method (general relay thread): epoll (with changelist)
0: : turn server id=11 created
0: : IPv4. TCP listener opened on : 0.0.0.0:3478
0: : IPv4. SCTP listener opened on : 0.0.0.0:3478
0: : turn server id=8 created
0: : turn server id=13 created
0: : IPv4. SCTP listener opened on : 0.0.0.0:3478
0: : IPv6. TCP listener opened on : :::3478
0: : IPv4. TCP listener opened on : 0.0.0.0:3478
0: : IPv4. SCTP listener opened on : 0.0.0.0:3478
0: : IPv6. SCTP listener opened on : :::3478
0: : IPv4. TCP listener opened on : 0.0.0.0:3478
0: : IPv4. SCTP listener opened on : 0.0.0.0:3478
0: : IPv4. TCP listener opened on : 0.0.0.0:3478
0: : IPv4. TCP listener opened on : 0.0.0.0:3478
0: : IPv6. SCTP listener opened on : :::3478
0: : IPv6. TCP listener opened on : :::3478
0: : IPv6. SCTP listener opened on : :::3478
0: : IO method (general relay thread): epoll (with changelist)
0: : IO method (general relay thread): epoll (with changelist)
0: : IO method (general relay thread): epoll (with changelist)
0: : IPv4. TCP listener opened on : 0.0.0.0:3478
0: : IO method (general relay thread): epoll (with changelist)
0: : IPv4. SCTP listener opened on : 0.0.0.0:3478
0: : turn server id=14 created
0: : turn server id=16 created
0: : IO method (general relay thread): epoll (with changelist)
0: : IPv4. TCP listener opened on : 0.0.0.0:3478
0: : IO method (general relay thread): epoll (with changelist)
0: : IPv6. TCP listener opened on : :::3478
0: : IO method (general relay thread): epoll (with changelist)
0: : IPv6. SCTP listener opened on : :::3478
0: : turn server id=12 created
0: : IO method (general relay thread): epoll (with changelist)
0: : IO method (general relay thread): epoll (with changelist)
0: : turn server id=20 created
0: : IO method (general relay thread): epoll (with changelist)
0: : IPv6. TCP listener opened on : :::3478
0: : IO method (general relay thread): epoll (with changelist)
0: : turn server id=22 created
0: : IPv6. SCTP listener opened on : :::3478
0: : turn server id=7 created
0: : IPv4. SCTP listener opened on : 0.0.0.0:3478
0: : turn server id=24 created
0: : IO method (general relay thread): epoll (with changelist)
0: : IPv6. SCTP listener opened on : :::3478
0: : IPv4. TCP listener opened on : 0.0.0.0:3478
0: : IO method (general relay thread): epoll (with changelist)
0: : IPv4. TCP listener opened on : 0.0.0.0:3478
0: : IPv4. SCTP listener opened on : 0.0.0.0:3478
0: : IPv4. TCP listener opened on : 0.0.0.0:3478
0: : turn server id=25 created
0: : turn server id=18 created
0: : IPv6. SCTP listener opened on : :::3478
0: : turn server id=19 created
0: : IPv4. SCTP listener opened on : 0.0.0.0:3478
0: : IPv4. SCTP listener opened on : 0.0.0.0:3478
0: : IPv4. SCTP listener opened on : 0.0.0.0:3478
0: : IO method (general relay thread): epoll (with changelist)
0: : IPv4. TCP listener opened on : 0.0.0.0:3478
0: : turn server id=23 created
0: : IPv4. SCTP listener opened on : 0.0.0.0:3478
0: : IO method (general relay thread): epoll (with changelist)
0: : IPv4. TCP listener opened on : 0.0.0.0:3478
0: : IO method (general relay thread): epoll (with changelist)
0: : IO method (general relay thread): epoll (with changelist)
0: : IO method (general relay thread): epoll (with changelist)
0: : turn server id=29 created
0: : turn server id=28 created
0: : turn server id=29 created
0: : turn server id=28 created
0: : IPv4. SCTP listener opened on : 0.0.0.0:3478
0: : IPv4. SCTP listener opened on : 0.0.0.0:3478
0: : IPv6. TCP listener opened on : :::3478
0: : turn server id=17 created
0: : turn server id=21 created
0: : IPv6. SCTP listener opened on : :::3478
0: : turn server id=26 created
0: : IPv4. SCTP listener opened on : 0.0.0.0:3478
0: : IPv4. TCP listener opened on : 0.0.0.0:3478
0: : IPv4. SCTP listener opened on : 0.0.0.0:3478
0: : IPv6. SCTP listener opened on : :::3478
0: : IPv6. TCP listener opened on : :::3478
0: : IPv6. TCP listener opened on : :::3478
0: : IPv6. TCP listener opened on : :::3478
0: : IPv4. TCP listener opened on : 0.0.0.0:3478
0: : turn server id=15 created
0: : IPv4. SCTP listener opened on : 0.0.0.0:3478
0: : IPv6. SCTP listener opened on : :::3478
0: : turn server id=27 created
0: : IPv6. TCP listener opened on : :::3478
0: : IPv6. SCTP listener opened on : :::3478
0: : IPv4. SCTP listener opened on : 0.0.0.0:3478
0: : IPv6. TCP listener opened on : :::3478
0: : turn server id=30 created
0: : IPv4. SCTP listener opened on : 0.0.0.0:3478
0: : IPv4. SCTP listener opened on : 0.0.0.0:3478
0: : turn server id=31 created
0: : IPv4. SCTP listener opened on : 0.0.0.0:3478
0: : IPv4. UDP listener opened on: 0.0.0.0:3478
0: : IPv4. TCP listener opened on : 0.0.0.0:3478
0: : IPv4. SCTP listener opened on : 0.0.0.0:3478
0: : IPv6. TCP listener ope

</details>

**Comment by ehfd** [comment]
Ah. Different issue. You cannot use the GLX Desktop when you already have an X11 server running.

**Comment by ehfd** [comment]
https://github.com/selkies-project/docker-nvidia-glx-desktop#i-want-to-share-one-gpu-with-multiple-containers-to-run-gui-workloads

**Comment by jmakov** [comment]
Beautiful, works. Thank you very much for the quick response and explaining what I did wrong.
